"""update role_permission table

Revision ID: 06bd05480a35
Revises: 2755aa768734
Create Date: 2026-01-09 12:15:44.857053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bd05480a35'
down_revision: Union[str, None] = '2755aa768734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('role_permissions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('role_permissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('role_permissions_permission_id_fkey', 'role_permissions', type_='foreignkey')
    op.drop_constraint('role_permissions_role_id_fkey', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'app_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_role_id_fkey', 'role_permissions', 'app_roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('role_permissions_permission_id_fkey', 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.drop_column('role_permissions', 'created_at')
    op.drop_column('role_permissions', 'is_active')
    op.drop_column('role_permissions', 'id')
    # ### end Alembic commands ###
