"""remove category from topics

Revision ID: 0d548a2402c8
Revises: 74a7ff881e90
Create Date: 2025-11-26 11:42:48.827028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d548a2402c8'
down_revision: Union[str, None] = '74a7ff881e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
