"""add_relationships_and_missing_tables

Revision ID: 1eb4b04151e5
Revises: 0d548a2402c8
Create Date: 2025-11-28 11:02:41.170157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb4b04151e5'
down_revision: Union[str, None] = '0d548a2402c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
