"""Add for role is active and created at

Revision ID: 240e0736053b
Revises: 6aabfaf4fa80
Create Date: 2026-01-09 10:47:34.263827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240e0736053b'
down_revision: Union[str, None] = '6aabfaf4fa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_roles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('app_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_roles', 'created_at')
    op.drop_column('app_roles', 'is_active')
    # ### end Alembic commands ###
