"""Add for permission  is active and created at

Revision ID: 2755aa768734
Revises: 240e0736053b
Create Date: 2026-01-09 11:38:06.168992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2755aa768734'
down_revision: Union[str, None] = '240e0736053b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'created_at')
    op.drop_column('permissions', 'is_active')
    # ### end Alembic commands ###
