"""Add Super Admin role

Revision ID: 3a21a80a0066
Revises: e2b7ae5c17c2
Create Date: 2025-11-29 06:46:17.565278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a21a80a0066'
down_revision: Union[str, None] = 'e2b7ae5c17c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'attended',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_bookings_session_id'), 'bookings', ['session_id'], unique=False)
    op.create_index(op.f('ix_bookings_student_id'), 'bookings', ['student_id'], unique=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('sessions', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'current_attendees',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'status',
               existing_type=postgresql.ENUM('active', 'cancelled', 'completed', 'upcoming', name='session_status'),
               nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_sessions_start_time'), 'sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_sessions_topic_id'), 'sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_sessions_trainer_id'), 'sessions', ['trainer_id'], unique=False)
    op.alter_column('topic_prerequisites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'topics', ['name'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('student', 'trainer', 'admin', name='user_roles'),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('student', 'trainer', 'admin', name='user_roles'),
               nullable=True)
    op.drop_constraint(None, 'topics', type_='unique')
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('topic_prerequisites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_sessions_trainer_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_topic_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_start_time'), table_name='sessions')
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sessions', 'status',
               existing_type=postgresql.ENUM('active', 'cancelled', 'completed', 'upcoming', name='session_status'),
               nullable=True)
    op.alter_column('sessions', 'current_attendees',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_bookings_student_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_session_id'), table_name='bookings')
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'attended',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
