"""update user role

Revision ID: 3fdfcd13036e
Revises: 06bd05480a35
Create Date: 2026-01-10 02:31:29.766173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fdfcd13036e'
down_revision: Union[str, None] = '06bd05480a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user_roles', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('app_user_roles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('app_user_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('app_user_roles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_user_role', 'app_user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'app_user_roles', type_='unique')
    op.drop_column('app_user_roles', 'updated_at')
    op.drop_column('app_user_roles', 'created_at')
    op.drop_column('app_user_roles', 'is_active')
    op.drop_column('app_user_roles', 'id')
    # ### end Alembic commands ###
